[[intro]]

== Introduction

The RISC-V Server Platform Test specification defines a set of tests to verify if the
requirements specified in the RISC-V Server Platform specification, along with
specifications included by reference, are implemented. The tests specified in
this specification are not intended to exhaustively verify the implementation.
Future versions of this specification may include more exhaustive tests.

The Server Platform specification builds on top of the Server SoC,
Boot and Runtime Services and Platform Security specifications, which
in turn have their own test specifications and/or compliance requirements.
This test specification does not duplicate requirements in these dependent
test specification, but provides additional tests on top of the tests
already defined in these other documents.  This test specification does
include overall platform tests requiring functionality that is first combined
in this specification.

The tests in this specification are documented use the following format:

[width=100%]
[%header, cols="8,20"]
|===
| TEST_ID#       ^| Test algorithm
| AB_CAT_NNN_MMM a| The `CAT_NNN` identifies a requirement in the RISC-V Server
                    SoC specification. Each requirement is associated with one
                    or more tests identified by `MMM`. The test IDs are prefixed
                    with two character prefix - `AB`.                          +
                                                                               +
                    If character in position `A` is `M` then the test is for a
                    requirement that MUST be supported and this test MUST pass.
                    If character in position `A` is `O` then the test is for a
                    requirement that SHOULD or MAY be supported; such tests may
                    be skipped if the requirement is not implemented. The tests
                    record if optional features were present in the test output
                    log.                                                       +
                                                                               +
                    The character in position `B` indicates the nature of the 
                    test. If this character is `F` then the test exercises some
                    or all of the functionality associated with the feature. If
                    the character is `E` then the test determines for evidence 
                    that the feature is implemented (e.g., check ACPI tables) 
                    but does not functionally exercise the feature.  If the
		    character is `C` then the test directly verifies
		    requirements which can only be tested using a combination
		    of features specified in the Server Platform document and/or
		    features incorporated by reference from another
		    specification.
                   
|===

This specification groups the tests in the following broad categories:

* Hardware
* Firmware
* Security

=== Glossary

Most terminology has the standard RISC-V meaning. This table captures other
terms used in the document.

.Terms and definitions
[width=90%]
[%header, cols="5,20"]
|===
| Term            ^| Definition
|===
