== Server Platform Test Specification

=== Server Platform Hardware Requirements

==== RISC-V Harts

[width=100%]
[%header, cols="8,25"]
|===
| ID#            ^| Algorithm
| `ME_RVA_010_010` a| For each application processor hart:

                    . Determine the ISA node in ACPI RHCT table for that hart.
                    . Parse the ISA string in the ISA node and verify that all
                      mandatory extensions are supported.
                    . Verify that the ISA strings of all harts in the RHCT table
                      are the same.
                    . Report the ISA string.
| `ME_RVA_020_010`  | See `T_RVA_010_010`.
| `ME_RVA_030_010` a| . The `T_RVA_010_010` verifies that all ISA strings are
                      identical.
                    . For each ISA extension reported in the ISA string, if
                      there are CSRs associated with that extension, then probe
                      the CSR to determine the width of the CSR fields and the
                      legal encodings on each application processor hart. The
                      CSR field widths and legal encodings supported by each
                      hart must match that of hart 0.
| `ME_RVA_040_010`  | See `ME_RVA_030_010`.
| `ME_RVA_050_010` a| No test.
| `MF_RVA_060_010` a| Install 4 instruction address match triggers using the debug
                    triggers SBI and verify that each trigger fires.
| `MF_RVA_060_020` a| Install 4 load address match triggers using the debug
                    triggers SBI and verify that each trigger fires.
| `MF_RVA_060_030` a| Install 4 store address match triggers using the debug
                    triggers SBI and verify that each trigger fires.
| `MF_RVA_060_040` a| Install an `icount` trigger using the debug triggers SBI and
                    verify single-step.
| `MF_RVA_060_050` a| . Install an interrupt trigger to match supervisor timer
                      interrupt using the debug triggers SBI.
                    . Program a timer deadline in `stimecmp`
                    . Verify that the trigger fires on reaching the programmed
                      deadline.
| `MF_RVA_060_060` a| . Install an exception trigger to match ECALL to S-mode
                      exception using the debug triggers SBI.
                    . Transition to U-mode and invoke an ECALL.
                    . Verify that the trigger fires.
| `MF_RVA_060_070` a| . Verify `hcontext` exists.
                    . Repeat `MF_RVA_060_010` and `MF_RVA_060_050` with a matching
                      and non-matching `hcontext` value.
| `ME_RVA_060_080` a| . Install and read-back triggers with VMID values between 0
                      and `VMIDLEN`.
| `MF_RVA_060_090` a| . Verify `scontext` exists.
                    . Repeat MF_RVA_060_010 and MF_RVA_060_050 with a matching
                      and non-matching `scontext` value.
| `ME_RVA_060_100` a| . Install and read-back triggers with ASID values between 0
                      and `ASIDLEN`.
| `ME_RVA_070_010` a| . Request delegation of all HPM counters using the SBI.
                    . Verify at least 6 programmable HPM counter are implemented.
                    . Verify that the `scountovf` CSR is implemented
                    . Verify `cycles` and `instret` are writeable.
                    . Verify ability to toggle counter enable for each
                      implemented HPM, `cycles`, and `instret` counters.
|===

<<<

==== RISC-V SoC

[width=100%]
[%header, cols="8,25"]
|===
| ID#            ^| Algorithm
| `ME_HSOC_010_010` | The Server SoC tests must pass cite:[ServerSoCTest].
| `MC_HSOC_010_020` | Parse the ACPI RHCT table to determine the firmware-reported
		      time base frequency and verify it is equal to 1 GHz.

		      This partially tests the product of the Server SoC
		      requirement CTI_010 (incorporated by reference
		      in the Server Platform requirement HSOC_010) and
		      the Boot & Runtime Services specification
		      section 2.1 (incorporated by reference in the
		      Server Platform requirement FIRM_010).
| `MC_HSOC_010_030` | Locate the ACPI _LPI objects for each RISC-V application
		      processor hart. If present, verify that the __Architectural
		      Context Lost Flags__ have bit 0 set to 0, indicating no
		      loss of timer context for each supported low-power idle
		      state.

		      This partially tests the product of the Server SoC
		      requirement CTI_020 (incorporated by reference
		      in the Server Platform requirement HSOC_010) and
		      the Boot & Runtime Services specification
		      section 2.1 (incorporated by reference in the
		      Server Platform requirement FIRM_010).
| `MC_HSOC_010_040` | For each application processor hart:

                      . Determine the ISA node in ACPI RHCT table for that hart.
                      . Parse the ISA string in the ISA node and verify that Ssaia
                        extension is supported.
                      . Parse the RINTC structure in ACPI MADT tables to verify that
                        the interrupt controller type for the hart is IMSIC.

		      This partially tests the product of the Server SoC
		      requirements IIC_010 and IIC_020 (incorporated by reference
		      in the Server Platform requirement HSOC_010) and
		      the Boot & Runtime Services specification
		      section 2.1 (incorporated by reference in the
		      Server Platform requirement FIRM_010).
| `MC_HSOC_010_050` | Verify the number of supported supervisor mode interrupt
                      identities in IMSIC structure of the ACPI MADT table is at
                      least 255.

		      This partially tests the product of the Server SoC
		      requirement IIC_050 (incorporated by reference
		      in the Server Platform requirement HSOC_010) and
		      the Boot & Runtime Services specification
		      section 2.1 (incorporated by reference in the
		      Server Platform requirement FIRM_010).
| `MC_HSOC_010_060` | Verify the number of supported guest mode interrupt
                      identities in IMSIC structure of the ACPI MADT table is at
                      least 63.

		      This partially tests the product of the Server SoC
		      requirement IIC_060 (incorporated by reference
		      in the Server Platform requirement HSOC_010) and
		      the Boot & Runtime Services specification
		      section 2.1 (incorporated by reference in the
		      Server Platform requirement FIRM_010).
| `ME_HSOC_020_010` | _FIXME_.
|===

<<<

==== Peripherals

[width=100%]
[%header, cols="8,25"]
|===
| ID#            ^| Algorithm
| `ME_HPER_010_010` | _FIXME_.
| `MF_HPER_020_010` | _FIXME_.
| `MF_HPER_030_010` | _FIXME XHCI test validating register values_.
| `MF_HPER_040_010` | _FIXME XHCI test validating register values_.
| `MF_HPER_050_010` | _FIXME AHCI test validating register values_.
| `MF_HPER_060_010` | _FIXME AHCI test validating register values_.
| `MF_HPER_070_010` | _FIXME UEFI RT based test_.
| `MF_HPER_080_010` | _FIXME_.
| `MF_HPER_090_010` | _FIXME_.
|===

<<<

=== Server Platform Firmware Requirements

[width=100%]
[%header, cols="8,25"]
|===
| ID#            ^| Algorithm
| `ME_FIRM_010_010` | The BRS-I tests must pass cite:[BRSTest].
| `MC_FIRM_010_020` | Parse the ACPI RHCT table to determine the firmware-reported
		      time base frequency and verify it is equal to 1 GHz.

		      This partially tests the product of the Server SoC
		      requirement CTI_010 (incorporated by reference
		      in the Server Platform requirement HSOC_010) and
		      the Boot & Runtime Services specification
		      section 2.1 (incorporated by reference in the
		      Server Platform requirement FIRM_010).
| `MC_FIRM_010_030` | Locate the ACPI _LPI objects for each RISC-V application
		      processor hart. If present, verify that the __Architectural
		      Context Lost Flags__ have bit 0 set to 0, indicating no
		      loss of timer context for each supported low-power idle
		      state.

		      This partially tests the product of the Server SoC
		      requirement CTI_020 (incorporated by reference
		      in the Server Platform requirement HSOC_010) and
		      the Boot & Runtime Services specification
		      section 2.1 (incorporated by reference in the
		      Server Platform requirement FIRM_010).
| `MC_FIRM_010_040` | For each application processor hart:

                      . Determine the ISA node in ACPI RHCT table for that hart.
                      . Parse the ISA string in the ISA node and verify that Ssaia
                        extension is supported.
                      . Parse the RINTC structure in ACPI MADT tables to verify that
                        the interrupt controller type for the hart is IMSIC.

		      This partially tests the product of the Server SoC
		      requirements IIC_010 and IIC_020 (incorporated by reference
		      in the Server Platform requirement HSOC_010) and
		      the Boot & Runtime Services specification
		      section 2.1 (incorporated by reference in the
		      Server Platform requirement FIRM_010).
| `MC_FIRM_010_050` | Verify the number of supported supervisor mode interrupt
                      identities in IMSIC structure of the ACPI MADT table is at
                      least 255.

		      This partially tests the product of the Server SoC
		      requirement IIC_050 (incorporated by reference
		      in the Server Platform requirement HSOC_010) and
		      the Boot & Runtime Services specification
		      section 2.1 (incorporated by reference in the
		      Server Platform requirement FIRM_010).
| `MC_FIRM_010_060` | Verify the number of supported guest mode interrupt
                      identities in IMSIC structure of the ACPI MADT table is at
                      least 63.

		      This partially tests the product of the Server SoC
		      requirement IIC_060 (incorporated by reference
		      in the Server Platform requirement HSOC_010) and
		      the Boot & Runtime Services specification
		      section 2.1 (incorporated by reference in the
		      Server Platform requirement FIRM_010).
| `ME_FIRM_020_010` | _FIXME_.
| `ME_FIRM_030_010` | _FIXME_.
| `ME_FIRM_040_010` | _FIXME_.
| `ME_FIRM_050_010` | _FIXME_.
| `ME_FIRM_060_010` | _FIXME_.
| `ME_FIRM_070_010` | _FIXME_.
| `ME_FIRM_080_010` | _FIXME_.
| `ME_FIRM_090_010` | _FIXME_.
| `ME_FIRM_100_010` | _FIXME_.
| `ME_FIRM_110_010` | _FIXME_.
|===

<<<

=== Server Platform Security Requirements

[width=100%]
[%header, cols="8,25"]
|===
| ID#            ^| Algorithm
| `ME_SEC_010_010`  | _FIXME_
| `ME_SEC_011_010`  | _FIXME_
| `ME_SEC_012_010`  | _FIXME_
| `ME_SEC_020_010`  | _FIXME_
| `ME_SEC_030_010`  | _FIXME_
| `ME_SEC_040_010`  | _FIXME_
| `ME_SEC_050_010`  | _FIXME_
| `ME_SEC_060_010`  | _FIXME_
|===

<<<
